export const lancamentos = [
  {
    id_lancamento: 2,
    id_usuario: 1,
    descricao: "Mercado",
    valor: 100,
    id_categoria: 2,
    tipo: "D",
    dt_lancamento: "2024-09-15",
    categoria: "Viagens",
    icone: "https://picsum.photos/50/50",
  },
  {
    id_lancamento: 1,
    id_usuario: 1,
    descricao: "Cinemark",
    valor: 60,
    id_categoria: 2,
    tipo: "D",
    dt_lancamento: "2024-09-14",
    categoria: "Viagens",
    icone: "https://picsum.photos/50/50",
  },
  {
    id_lancamento: 4,
    id_usuario: 1,
    descricao: "Salário",
    valor: 10000,
    id_categoria: 2,
    tipo: "R",
    dt_lancamento: "2024-09-01",
    categoria: "Viagens",
    icone: "https://picsum.photos/50/50",
  },
  {
    id_lancamento: 3,
    id_usuario: 1,
    descricao: "IPVA",
    valor: 1500,
    id_categoria: 2,
    tipo: "D",
    dt_lancamento: "2024-08-01",
    categoria: "Viagens",
    icone: "https://picsum.photos/50/50",
  },
];

export const categorias = [
  {
    id_categoria: 1,
    id_usuario: 1,
    categoria: "Alimentação",
    icone: "https://picsum.photos/50/50",
  },
  {
    id_categoria: 2,
    id_usuario: 1,
    categoria: "Viagens",
    icone: "https://picsum.photos/50/50",
  },
  {
    id_categoria: 3,
    id_usuario: 1,
    categoria: "Transporte",
    icone: "https://picsum.photos/50/50",
  },
  {
    id_categoria: 4,
    id_usuario: 1,
    categoria: "Educação",
    icone: "https://picsum.photos/50/50",
  },
  {
    id_categoria: 5,
    id_usuario: 1,
    categoria: "Saúde",
    icone: "https://picsum.photos/50/50",
  },
];
